<a href="https://colab.research.google.com/github/rabindramahato3/AppliedAI/blob/main/1_Python_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Python: without numpy or sklearn </h1>

#<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
# here A and B are list of lists
def matrix_mul(A, B):
    # write your code
    # matices are taken by list of lists
    # get rows and columns of both matrices A and B
    rowsA = len(A)
    colsA = len(A[0])
    rowsB = len(B)
    colsB = len(B[0])

    # check whether multiplication is possible.
    # i.e., colsA should be equal to rowsB
    if colsA != rowsB:
      return  
    else:
      # resultant matrix will be of size (rowsA, colsB) 
      # C(rowsA, colsB)  be a matrix to store multiplication result
      # initializing it with zeroes
      result =[[0 for c in range(colsB)] for r in range(rowsA)]
      # print(result)
      # Matrix multiplication
      # result(i,j) = summation(A(i,k) + B(k,j)) 
      # for i : 1...rowsA, j:1...colsB, k:1...rowsB/colsA

      for i in range(rowsA):
        for j in range(colsB):
          for k in range(rowsB):
            result[i][j] = result[i][j] + A[i][k] * B[k][j]
            # print(f'({i},{j})= {result[i][j]}')
      return result


In [ ]:
def printMatrix(M):
    '''
    This function prints the matrix by taking list of lists as argument
    '''
    for r in M:
        print(r)   

In [ ]:
A1 = [[1,2],[3,4]]
B1 = [[1,4],[5,6], [7,8], [9,6]]

A2 = [[1, 3, 4],[2, 5, 7],[5, 9, 6]]
B2 = [[1, 0, 0],[0, 1, 0],[0, 0, 1]]

A3 = [[1,2],[3,4]]
B3 = [[1,2,3,4,5],[5,6,7,8,9]]

A = [A1, A2, A3]
B = [B1, B2, B3]

for A, B in zip(A, B):

  print('\nA = ')
  printMatrix(A)
  print('\nB = ')
  printMatrix(B)
  print('\nA*B = ')
  result = matrix_mul(A, B)
  if result:
    printMatrix(result)
  else:
    print('Not Possible')


A = 
[1, 2]
[3, 4]

B = 
[1, 4]
[5, 6]
[7, 8]
[9, 6]

A*B = 
Not Possible

A = 
[1, 3, 4]
[2, 5, 7]
[5, 9, 6]

B = 
[1, 0, 0]
[0, 1, 0]
[0, 0, 1]

A*B = 
[1, 3, 4]
[2, 5, 7]
[5, 9, 6]

A = 
[1, 2]
[3, 4]

B = 
[1, 2, 3, 4, 5]
[5, 6, 7, 8, 9]

A*B = 
[11, 14, 17, 20, 23]
[23, 30, 37, 44, 51]


#<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [ ]:
from random import uniform
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
def pick_a_number_from_list(A):
    # your code here for picking an element from with the probability propotional to its magnitude
    # correction : else zero will not be selected
    Am = [i+1 for i in A]

    # 1. Compute sum of all elements in list
    S = sum(Am)

    # 2. normalize the list
    normA = [(i/S) for i in Am]

    # 3. cummalative normalized sum
    summ = 0
    cummNormSum = []
    for i in range(len(normA)):
      summ += normA[i]
      cummNormSum.append(summ)

    # print(cummNormSum)
    # sample one-value uniformly in range (0,1)
    random_value = uniform(0.0, 1.0)
    # print(random_value)

    # proportional sampling
    for index in range(len(cummNormSum)):
      if random_value <= cummNormSum[index]:
        return A[index]




In [ ]:
def sampling_based_on_magnitued():
    f = dict.fromkeys(A, 0)
    for i in range(1,100):
        number = pick_a_number_from_list(A)
        print(number)
        f[number] += 1

    print('\nSummary of the Sampling :')
    for k, v in sorted(f.items(), key = lambda item : item[1], reverse = True):
      # print(f'f({k}) = {v}')
      print(f'[ f({k}) : {v} ]', end=" > ")
    

In [ ]:
A = [0, 5, 27, 6, 13, 28, 100, 45, 10, 79]
# A = [2,6,1.2,5.8,20]

# calling function
sampling_based_on_magnitued()


100
100
13
45
100
79
45
27
28
28
79
28
6
79
100
100
10
10
100
100
100
28
100
100
45
28
100
79
100
28
27
79
79
79
45
100
13
100
13
100
27
100
79
100
100
100
79
100
79
100
100
100
27
10
27
100
28
100
45
100
28
28
28
79
79
79
27
45
45
45
27
79
28
100
13
45
13
28
6
100
28
79
79
100
100
79
6
100
27
27
79
28
28
100
45
100
100
10
79

Summary of the Sampling :
[ f(100) : 34 ] > [ f(79) : 19 ] > [ f(28) : 15 ] > [ f(45) : 10 ] > [ f(27) : 9 ] > [ f(13) : 5 ] > [ f(10) : 4 ] > [ f(6) : 3 ] > [ f(0) : 0 ] > [ f(5) : 0 ] > 

#<h3> Q3: Replace the digits in the string with '#'</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [ ]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
# String: it will be the input to your program
def replace_digits(String):
    # write your code
    # 1. remove all non-digits
    digitString = re.sub(r'\D', '', String)

    # 2. replace digits with '#'
    hashString = re.sub(r'\d', '#', digitString)
    return  hashString # modified string which is after replacing the # with digits



In [ ]:

A1 = '234'
A2 = 'a2b3c4'
A3 = 'abc'
A4 = '#2a$#b%c%561#'
# replace_digits(String)
strings = [A1, A2, A3, A4]
print('For strings output is :')
for string in strings:
  replacedDigits = replace_digits(string)
  print(f'{string} --> {replacedDigits}')

For strings output is :
234 --> ###
a2b3c4 --> ###
abc --> 
#2a$#b%c%561# --> ####


#<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
def display_dash_board(students, marks):

  # create a dictionary with students as key and marks as values
  dashboard = dict(zip(Students, Marks))
  
  # write code for computing top top 5 students
  top_5_students = sorted(dashboard.items(), key = lambda item:item[1], reverse=True)[:5]

  # write code for computing top least 5 students
  least_5_students = sorted(dashboard.items(), key = lambda item:item[1])[:5]
  
  # write code for computing top least 5 students
  min_mark = min(marks)
  max_mark = max(marks)
  difference = max_mark - min_mark
  perc_25 = difference*0.25
  perc_75 = difference*0.75

  students_within_25_and_75 = dict()
  for key, value in dashboard.items():
    if int(value) >= perc_25 and int(value) <= perc_75:
      students_within_25_and_75[key] = value
  students_within_25_and_75 = sorted(students_within_25_and_75.items(), key = lambda item:item[1])
  return top_5_students, least_5_students, students_within_25_and_75



In [ ]:
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

# main program
top_5_students, least_5_students, students_within_25_and_75 = display_dash_board(Students, Marks)

print('--- DASHBOARD ---')
print(' STUDENT  \t  MARK ')
print('--------- \t ------')
for s, m in zip(Students, Marks):
  print(f'{s} --------  {m}')

print('\nA. Top 5 students in descending order of marks :')
for student in top_5_students:
  print(student[0],' : ',student[1])

print('\nB. Least 5 students in increasing order of marks :')
for student in least_5_students:
  print(student[0],' : ',student[1])

print('\nC. Students having marks between 25 pencentile and 75 percentile :')
for student in students_within_25_and_75:
  print(student[0],' : ',student[1])

--- DASHBOARD ---
 STUDENT  	  MARK 
--------- 	 ------
student1 --------  45
student2 --------  78
student3 --------  12
student4 --------  14
student5 --------  48
student6 --------  43
student7 --------  47
student8 --------  98
student9 --------  35
student10 --------  80

A. Top 5 students in descending order of marks :
student8  :  98
student10  :  80
student2  :  78
student5  :  48
student7  :  47

B. Least 5 students in increasing order of marks :
student3  :  12
student4  :  14
student9  :  35
student6  :  43
student1  :  45

C. Students having marks between 25 pencentile and 75 percentile :
student9  :  35
student6  :  43
student1  :  45
student7  :  47
student5  :  48


#<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [ ]:
import math

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure


# here S is list of tuples and P is a tuple ot len=2
def closest_points_to_p(S, P):
  # write your code here
  
  cosineDistanceList = dict()
  for x,y in S:
    # calculate cosine distance using formulae
    num = x*P[0] + y*P[1]
    den = math.sqrt(x**2 + y**2) * math.sqrt(P[0]**2 + P[1]**2)
    cosineDistance = math.acos(num/den)
    cosineDistanceList[(x,y)] = cosineDistance

    closest_points_to_p = sorted(cosineDistanceList.items(), key=lambda item:item[1])
  return closest_points_to_p  # its list of tuples



In [ ]:
S= [(1,2), (3,4), (-1,1), (6,-7), (0, 6), (-5,-8), (-1,-1), (6,0), (1,-1)]
P= (3,-4)

# main program
points = closest_points_to_p(S, P)
print(f'5 closest points(based on cosine distance)\n\
 in S {S} \n\
 from P {P} :')
for point in points[:5]:
  print(point[0]) #print the returned values

5 closest points(based on cosine distance)
 in S [(1, 2), (3, 4), (-1, 1), (6, -7), (0, 6), (-5, -8), (-1, -1), (6, 0), (1, -1)] 
 from P (3, -4) :
(6, -7)
(1, -1)
(6, 0)
(-5, -8)
(-1, -1)


#<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [ ]:
import math
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def i_am_the_one(red,blue,line):
    # your code
    # seperate coefficeints
    a = line.split('x')
    b = a[1].split('y')
    coeff = tuple(map(float, [a[0], b[0], b[1]]))

    # check side of one red and one blue point
    side_red = getSide(coeff, red[0]) if len(red) != 0 else 0
    side_blue = getSide(coeff, blue[0]) if len(blue) != 0 else 0

    # check all other red points lies on one side
    for i in range(1,len(red)):
      if side_red != getSide(coeff, red[i]):
        return 'NO'

    # check all other blue points lies on one side
    for i in range(1,len(blue)):
      if side_blue != getSide(coeff, blue[i]):
        return 'NO'

    # if both red and blue points lies on same side
    if side_red == side_blue:
      return 'NO'

    # if all red points lie on one side and blue on other side
    return 'YES'



In [ ]:
# function to determine side of point
def getSide(line, point):
  fx = line[0] * point[0] + line[1] * point[1] + line[2]
  if fx > 0:
    return 1
  elif fx < 0:
    return -1
  elif fx == 0:
    return 0

In [ ]:
# given data points and lines
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5", "1x+0y+6"]

# main program
print(f'Red Points : {Red}')
print(f'Blue Points : {Blue}')
print(f'Line Equations : {Lines} \n')
for i in Lines:
  yes_or_no = i_am_the_one(Red, Blue, i)
  print(f'Line {i} seperates Red and Blue Points : {yes_or_no}')


Red Points : [(1, 1), (2, 1), (4, 2), (2, 4), (-1, 4)]
Blue Points : [(-2, -1), (-1, -2), (-3, -2), (-3, -1), (1, -3)]
Line Equations : ['1x+1y+0', '1x-1y+0', '1x+0y-3', '0x+1y-0.5', '1x+0y+6'] 

Line 1x+1y+0 seperates Red and Blue Points : YES
Line 1x-1y+0 seperates Red and Blue Points : NO
Line 1x+0y-3 seperates Red and Blue Points : NO
Line 0x+1y-0.5 seperates Red and Blue Points : YES
Line 1x+0y+6 seperates Red and Blue Points : NO


#<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def curve_smoothing(string):
  # your code
  # split the comma seperated values
  s_list = string.split(',')

  # for every value in s_list if it is integer
  # if integer then smooth it 
  start_index = 0
  for index in range(len(s_list)):
    if s_list[index].isnumeric():
      s_list = smooth_it(s_list, start_index, index)
      start_index = index
    else:
      s_list[index] = 0

  # smoothing all of values is missing after a number
  end_index = len(s_list) - 1
  s_list = smooth_it(s_list, start_index, end_index)
    
  return s_list




In [ ]:

def smooth_it(s_list, start_index, end_index):

  # finding mean
  T = 0
  for i in range(start_index, end_index+1):
    T += int(s_list[i])
  N = end_index - start_index + 1
  smoothed_value = T // N

  # updating the list
  for i in range(start_index, end_index+1):
        s_list[i] = str(smoothed_value)
        
  return s_list


In [ ]:
S1 = "_,_,30,_,_,_,50,_,_"
S2 = "_,_,_,24"
S3 = "40,_,_,_,60"
S4 = "80,_,_,_,_"
S = [S1, S2, S3, S4]

# main program
print('String Smoothing : ' )
for string in S:
  smoothed_values = curve_smoothing(string)
  smoothed_string = ",".join(smoothed_values)
  print(f' {string} \t>>  {smoothed_string}')

String Smoothing : 
 _,_,30,_,_,_,50,_,_ 	>>  10,10,12,12,12,12,4,4,4
 _,_,_,24 	>>  6,6,6,6
 40,_,_,_,60 	>>  20,20,20,20,20
 80,_,_,_,_ 	>>  16,16,16,16,16


#<h3> Q8: Compute conditional Probablities</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings



# you can free to change all these codes/structure
def compute_conditional_probabilites(A):
  # your code
  # print the output as per the instructions
  F, S = [], []
  for f, s in A:
    if f not in F:
      F.append(f)
    if s not in S:
      S.append(s)
  # print(F, S)

  i = 97
  for f in F:
    p = []
    for s in S:
      num, den = probability(f, s, A)
      p.append(f'P(F={f}|S={s})={num}/{den}')
    print(f'{chr(i)}. {", ".join(p)}')
    i +=1

In [ ]:
# calculate probability of happening f when s already happened in an event
def probability(f, s, event):
  num , den = 0, 0
  for i in range(len(event)):
    if event[i][1] == s:
      den += 1
      if event[i][0] == f:
        num += 1

  return num, den

In [ ]:
A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

print(f'A = {A}')
print('Conditional probabilites for A : \n')
compute_conditional_probabilites(A)

A = [['F1', 'S1'], ['F2', 'S2'], ['F3', 'S3'], ['F1', 'S2'], ['F2', 'S3'], ['F3', 'S2'], ['F2', 'S1'], ['F4', 'S1'], ['F4', 'S3'], ['F5', 'S1']]
Conditional probabilites for A : 

a. P(F=F1|S=S1)=1/4, P(F=F1|S=S2)=1/3, P(F=F1|S=S3)=0/3
b. P(F=F2|S=S1)=1/4, P(F=F2|S=S2)=1/3, P(F=F2|S=S3)=1/3
c. P(F=F3|S=S1)=0/4, P(F=F3|S=S2)=1/3, P(F=F3|S=S3)=1/3
d. P(F=F4|S=S1)=1/4, P(F=F4|S=S2)=0/3, P(F=F4|S=S3)=1/3
e. P(F=F5|S=S1)=1/4, P(F=F5|S=S2)=0/3, P(F=F5|S=S3)=0/3


#<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
    # your code
    # split the string and convert it into set
    s1 = set(S1.split())
    s2 = set(S2.split())

    # number of common words = length of set intersection (s1,s2)
    a = len(s1 & s2)

    # in S1 but not in S2 = set difference (s1, s2)
    b = sorted(list(s1 - s2), reverse=True)

    # in S2 but not in S1 = set difference (s2, s1)
    c = sorted(list(s2 - s1), reverse=True)

    return a, b, c



In [ ]:
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"


a,b,c = string_features(S1, S2)
print(f'S1 = {S1}')
print(f'S2 = {S2}')

print(f'\na. Number of common words between S1, S2 : {a}')
print(f'b. Words in S1 but not in S2 : {b}')
print(f'c. Words in S2 but not in S1 : {c}')

S1 = the first column F will contain only 5 uniques values
S2 = the second column S will contain only 3 uniques values

a. Number of common words between S1, S2 : 7
b. Words in S1 but not in S2 : ['first', 'F', '5']
c. Words in S2 but not in S1 : ['second', 'S', '3']


#<h3> Q10: Compute log loss</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def compute_log_loss(A):
    # your code
    n = len(A)
    loss = 0
    for y, y_score in A:
      loss += (y*log10(y_score) + (1-y)*log10(1-y_score))
    loss = -1/n * loss
    return loss



ln(x) = lim <sub><sub> n -> infinity</sub></sub> n(x<sup><sup>1/n</sup></sup> - 1)<br>

<br>
log<sub>b</sub>x = log<sub>k</sub>x / log<sub>k</sub>b = ln(x)/ln(b)

log<sub>10</sub>x = ln(x) / ln(10)

In [ ]:
def log10(x):
  return ln(x)/ln(10)

def ln(x):
  n = 999999999
  return n * ((x ** (1/n)) - 1)

In [ ]:
A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]

loss = compute_log_loss(A)
# print(loss)
print(f'A = {A}')
print('log loss for A is {0:.7f} approx.'.format(loss))

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
log loss for A is 0.4243099 approx.
